#!/usr/bin/env python3
"""Prepare the structured-recall dataset for HuggingFace publication.

Renders a ready-to-upload dataset directory (MIT license, dataset
card, flat JSONL views alongside the canonical nested JSON) from a
generated dataset file. Publication itself is a manual step — it
must run under the dataset owner's HuggingFace account:

::

    # 1. Generate the full dataset (deterministic, seed pinned)
    uv run python -m bench.memory.structured_corpus --preset full \
        --output /tmp/structured_recall_full.json

    # 2. Render the upload directory
    uv run python -m bench.memory.hf_publish \
        --dataset /tmp/structured_recall_full.json --output /tmp/hf-structured-recall

    # 3. Upload (OWNER ONLY - requires `huggingface_hub` login)
    hf auth login
    hf upload muxi-ai/structured-recall /tmp/hf-structured-recall \
        --repo-type dataset --commit-message "structured-recall v1.0"

This script never talks to the network.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import List, Optional

if __package__ in (None, ""):  # direct script invocation
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from bench.memory.structured_corpus import (  # noqa: E402
    CATEGORIES,
    DATASET_NAME,
    DATASET_SCHEMA_VERSION,
)

DEFAULT_REPO_ID = "muxi-ai/structured-recall"

DATASET_CARD = """---
license: mit
language:
- en
task_categories:
- question-answering
tags:
- memory
- benchmark
- knowledge-graph
- agents
- synthetic
pretty_name: MUXI Structured Recall
size_categories:
- n<1K
---

# MUXI Structured Recall

A benchmark for **structured memory recall** in AI agent systems: the
question categories that verbatim-text or flat-fact memory systems
cannot answer well, because they require a knowledge graph, a
temporal narrative layer, and cross-agent knowledge sharing.

Five categories ({question_count} questions total in this release):

| Category | Tests |
|----------|-------|
| `kg_relationship` | Entity-relationship recall (who recommended X for Y; emails, reference codes) |
| `temporal_validity` | What was true at a point in time (roles before/after changes) |
| `narrative_recall` | Day-level narrative memory (decisions and projects of a given date) |
| `cross_agent` | Knowledge produced by one agent, queried through another |
| `contradiction_detection` | Conflicting facts across sessions that should be surfaced, not silently merged |

Questions whose answers are verbatim tokens (emails, invoice/ticket
codes) carry `exact_strings`, enabling **exact-string recall**
measurement — semantic embeddings are notoriously weak at exact-token
matching, and this metric isolates that failure mode.

## Structure

- `structured_recall.json` — canonical nested dataset: cases ->
  sessions (dated, agent-attributed conversation turns), questions
  (with evidence session/turn ids), and a full ground-truth manifest
  (entities, relationships with turn-level provenance, daily log
  entries, injected contradictions).
- `data/sessions.jsonl` — flat view: one conversation session per line.
- `data/questions.jsonl` — flat view: one question per line.

## Generation

Fully synthetic and deterministic: generated by
`bench/memory/structured_corpus.py` in the
[MUXI runtime](https://github.com/muxi-ai) repository (seed
{seed}). No real conversations, personal data, or third-party
datasets are included; names, companies, and email domains are
fictional (`*.example.com`).

## Scoring

The reference runner (`bench/memory/structured_recall_runner.py`)
reports retrieval R@K / coverage / MRR per category, exact-string
recall, contradiction-detection precision/recall, and optional
LLM-judged answer accuracy.

## License

MIT. The generator, runner, and this dataset are released together;
regenerate at any scale with the seed of your choice.
"""


def flatten_sessions(dataset: dict) -> List[dict]:
    rows = []
    for case in dataset["cases"]:
        for session in case["sessions"]:
            rows.append(
                {
                    "case_id": case["case_id"],
                    "scenario": case["scenario"],
                    "session_id": session["session_id"],
                    "date": session["date"],
                    "agent_id": session["agent_id"],
                    "turns": session["turns"],
                }
            )
    return rows


def flatten_questions(dataset: dict) -> List[dict]:
    rows = []
    for case in dataset["cases"]:
        for question in case["questions"]:
            rows.append({"case_id": case["case_id"], **question})
    return rows


def render(dataset_path: Path, output_dir: Path) -> Path:
    with open(dataset_path, "r", encoding="utf-8") as handle:
        dataset = json.load(handle)
    if dataset.get("name") != DATASET_NAME:
        raise ValueError(
            f"Not a structured-recall dataset: name={dataset.get('name')!r} "
            f"(expected {DATASET_NAME!r})"
        )
    if sorted(dataset.get("generator", {}).get("categories", [])) != sorted(CATEGORIES):
        raise ValueError("Dataset categories do not match the current generator schema")

    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "data").mkdir(exist_ok=True)

    question_count = sum(len(case["questions"]) for case in dataset["cases"])
    card = DATASET_CARD.format(
        question_count=question_count,
        seed=dataset["generator"]["seed"],
    )
    (output_dir / "README.md").write_text(card, encoding="utf-8")

    canonical = output_dir / "structured_recall.json"
    with open(canonical, "w", encoding="utf-8") as handle:
        json.dump(dataset, handle, indent=2, sort_keys=True, ensure_ascii=False)
        handle.write("\n")

    for name, rows in (
        ("sessions.jsonl", flatten_sessions(dataset)),
        ("questions.jsonl", flatten_questions(dataset)),
    ):
        with open(output_dir / "data" / name, "w", encoding="utf-8") as handle:
            for row in rows:
                handle.write(json.dumps(row, sort_keys=True, ensure_ascii=False))
                handle.write("\n")

    return output_dir


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Render the structured-recall dataset into a HuggingFace-ready "
            "directory (does NOT upload)."
        )
    )
    parser.add_argument("--dataset", required=True, help="Generated dataset JSON.")
    parser.add_argument("--output", required=True, help="Output directory to render into.")
    parser.add_argument("--repo-id", default=DEFAULT_REPO_ID)
    args = parser.parse_args(argv)

    output = render(Path(args.dataset), Path(args.output))
    print(f"Rendered HuggingFace dataset directory: {output}")
    print(f"  schema: {DATASET_NAME} v{DATASET_SCHEMA_VERSION}")
    print("")
    print("To publish (dataset owner only):")
    print("  hf auth login")
    print(
        f"  hf upload {args.repo_id} {output} --repo-type dataset "
        f'--commit-message "structured-recall v{DATASET_SCHEMA_VERSION}"'
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
